language: cpp

compiler:
  - gcc
  - clang

env:
  - FIRST_ORDER=ON
  - FIRST_ORDER=OFF

before_install:
  - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_6.5-14_amd64.deb
  - sudo dpkg -i cuda-repo-ubuntu1204_6.5-14_amd64.deb
  - sudo apt-get update -qq
  - sudo apt-get install -qq gromacs
  - sudo apt-get install -qq doxygen
  - sudo apt-get install -qq liblapack-dev
  - sudo apt-get install -qq libblas-dev
  - sudo apt-get install -qq cuda-5-5

script:
  - git clone --depth 1 --branch 6.1 https://github.com/SimTk/openmm.git
  - cd openmm
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/OpenMM -DBUILD_TESTING=OFF -DOPENMM_BUILD_CPU_LIB=OFF -DOPENMM_BUILD_CUDA_LIB=ON -DOPENMM_BUILD_CUDA_TESTS=OFF -DOPENMM_BUILD_PYTHON_WRAPPERS=OFF -DOPENMM_BUILD_AMOEBA_PLUGIN=OFF -DOPENMM_BUILD_RPMD_PLUGIN=OFF -DOPENMM_BUILD_DRUDE_PLUGIN=OFF -DOPENMM_BUILD_PME_PLUGIN=OFF .
  - make
  - make install
  - cd ..
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/LTMDOpenMM -DOPENMM_DIR=$HOME/OpenMM -DOPENMM_SOURCE_DIR=openmm -DBUILD_FIRST_ORDER=$FIRST_ORDER .
  - make
  - make install

notifications:
  email: false
